Vagrant.configure("2") do |config|
    config.vm.provider :virtualbox do |v|
      v.memory = 2048 # RAM size
    end
  
    config.vm.define "vm-name"  do |config|
      config.vm.box = "bento/ubuntu-18.04" # Distro
      config.vm.hostname = "vm-name" 
      config.vm.network :private_network, ip: "10.10.10.10"
  
      # Ansible configuration
      config.vm.provision 'ansible' do |ansible|
        ansible.playbook = '../ansible/ansible.yml'
        ansible.groups = {
          'vm-name' => ['vm-name'],
          # Variables
          'vm-name:vars' => { 
            "registry_url" => "registry.medved.studio",
            "registry_user" => "admin",
            "registry_password" => "wiahieN3oo",
          }
        }
      end
    end
  end